on:
  - push

name: CI

jobs:
  client-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Lint
        working-directory: client
        run: |
          yarn lint

  client-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build
        working-directory: client
        run: |
          yarn build
